import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/toaster";
import AppLayout from "@/components/AppLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark overflow-x-hidden`}>
        <NextTopLoader
          color={"#ff0000"}
          initialPosition={0.08}
          height={2}
          easing="ease"
        />
        <Toaster />
          <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
