import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/toaster"
import AuthProvider from "./context/AuthProvider";
import AppLayout from "@/components/AppLayout";
//import { SocketProvider } from "./context/SocketProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <NextTopLoader
          color={"#ff0000"}
          initialPosition={0.08}
          height={2}
          easing="ease"
        />
        <AuthProvider>
            <Toaster/>
            <AppLayout>
              {children}
            </AppLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
